### ISSUE TITLE
"View More" link hidden behind events. Strange behavior.

### ISSUE THREAD

**Issue by terinjokes** [lyconic/fullcalendar.viewmore#2]
Hey!

I've attempted to enable on my fullcalendar at http://ufcampuscrusade.com/prayer_signup/.

Effectively what's happens is that the events are limited to amount I give, but the "View More" link is hidden behind the events. If you click on a day (which on my setup, loads the agenda_day view) and then switch back to the Month view, the events are gone entirely.

I have it fullcalendar.viewmore disabled right now (since, technically it's a live page), but if you want to see the error, let me know can I can uncomment the line.

**Comment by alassek** [comment]
Thanks for the feedback, that sounds like a bug. I'll see that Scott takes a look at this.

**Comment by sgreenfield** [comment]
This looks like an oversight on my part.  I will add functionality to solve this issue, but for now, here's a temporary solution that you could try.

fullCalendar calculates the height based on the number of events rendered to the calendar.  If you add a height parameter to the invocation of fullCalendar, does it work?  You'll have to play around with the number of pixels required render properly.  See below:

```
    $('#calendar').fullCalendar({
      height: 1200
    });
```

We clearly can't depend on the height parameter, so I will add functionality to accommodate users who don't supply a height to fullCalendar.

**Comment by terinjokes** [comment]
I added a height parameter, but it has the same issue as described.

**Comment by sgreenfield** [comment]
Thanks again for reporting this bug.  Do you have a development URL where I can see this in action?  At any rate, your bug report has led me to discover a couple of other bugs, which I have fixed and will deploy a new release soon.  I think there's a good chance that the bugs I have fixed will solve your issue.  I'll try to get it release some time today.

**Comment by terinjokes** [comment]
Sure thing.

Live FullCalendar (that is, without viewmore) is: http://ufcampuscrusade.com/prayer_signup/

FullCalendar with viewmore is: http://ufcampuscrusade.com/prayer_signup/index-viewmore.html

**Comment by sgreenfield** [comment]
Ok, I just uploaded a new version that should fix this and a few other bugs.  Make sure you have all of the **JavaScript dependencies** as well as the **CSS dependencies**, or it won't work.  I have updated the readme to show CSS dependencies (woops!).

The working example in the latest plugin version is very similar to yours, because it is a calendar with liquid dimensions.  Please let me know if this does not solve your issues.

Thanks,

Scott Greenfield

**Comment by terinjokes** [comment]
Sorry that I missed those CSS dependencies!

I still have an issue where the events disappear if you click on a day (which goes to the agenda view), then back navigate back to the month view, the events disappear. (the same links as above)

Also, can you add an option to the API to cause the "View More" to activate on hover? There's probably a way to make "View More" accept the clicks without the calendar below also, but unfortunately I'm too sick right now to even think about it.

**Comment by sgreenfield** [comment]
Regarding this: "if you click on a day (which goes to the agenda view), then back navigate back to the month view, the events disappear."  That is another bug, but fortunately an easy one for me to fix.

Regarding your last paragraph, I'm not entirely sure what you mean by "activate on hover"... the view more buttons already have a hover state which you can change.  The CSS that defines this is in viewmore.css.  If you meant something else, please specify.

In the mean time, I'm a bit busy with other stuff, but I'll try to get the dissapearing events bug fixed and deployed today or tomorrow.

It looks like you've elected to have the "view more" buttons go to the agenda view instead of displaying the "google calenderish" overlay.  If you are having problems with the overlay, feel free to let me know.  I should probably add an option to the API to allow the developer to choose the action of the "view more" button to either trigger the overlay or the agenda view.

Hope you feel better,

Scott Greenfield

**Comment by sgreenfield** [comment]
Marking this bug as resolved.
Opened new bug request for "disapearing events" bug.

https://github.com/lyconic/fullcalendar.viewmore/issues/#issue/4
